config/routes.rb
Rails.application.routes.draw do
  resources :papers
  get 'welcome/index'
  resources :authors
  root 'home#index'

  

  

end

app/models/application_record.rb
# By default all new Rails 5 applications will have application_record.rb.
# If you are migrating from Rails 4, then simply create app/models/application_record.rb
# as shown below and change all models to inherit from ApplicationRecord instead of ActiveRecord::Base.
# https://stackoverflow.com/questions/41387706/uninitialized-constant-applicationrecord-error#41388844
# https://blog.bigbinary.com/2015/12/28/application-record-in-rails-5.html
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :last_name, presence: true,
            length: { minimum: 5 }

  has_and_belongs_to_many :papers
  def name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end
  def new
    @author = Author.new
  end
  def edit
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to authors_path
  end

  private
  def author_params
    params.require(:author).permit(:first_name, :text, :last_name, :text, :homepage, :text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/author/new.html.erb
<h1>Newe Article Nice</h1>

<%= form_with scope: :author, local: true do |form| %>
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>

  <p>
    <%= form.label :homepage %><br>
    <%=form.text_field :homepage %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/authors/_form.html.erb
<%= form_with model: @author, local: true do |form| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited
        this auhtor from being saved:
      </h2>
      <ul>
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>

  <p>
    <%= form.label :homepage %><br>
    <%=form.text_field :homepage %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1> All Authors</h1>

<%= link_to 'Create new author', new_author_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Homepage</th>
  </tr>

  <% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= author.homepage %></td>
    <td><%= link_to "Show", author_path(author) %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Delete', author_path(author),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
  </tr>
  </tr>
  <% end %>
</table>

app/views/authors/new.html.erb
<h1>New Author Nice</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @author.homepage %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %>
<%= link_to 'Back', authors_path %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>It works! Paper Management System</h1>
You are seeing the rendered view of 'views/home/index.html.erb'
<%= link_to 'My Blog', controller: 'authors'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SWT II Intro Exercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>